### ISSUE TITLE
please add the support of dota2 dedicated server.

### ISSUE THREAD

**Issue by Svenmax** [n0tic/SteamServerCreationTool#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by n0tic** [comment]
According to SteamCMD I will need to add a feature that allows you to enter a username and password for your steam account.
"For SteamCMD, you will have to login to an existing Steam account since it is not available when logging in anonymously."

I had no plans of adding this feature but I am going to look into it. Consider this "under consideration" for now.

**Comment by n0tic** [comment]
I took some time adding this feature today. I was able to download Dota 2 and the rest should be simple launch option. Comment here once you have some feedback regarding the application. I'll leave this thread open for a couple of days before closing it.

Enjoy.

**Comment by Svenmax** [comment]
THX for the  great work. where can i find all the  launch option for dota2 ?

**Comment by n0tic** [comment]
From what I could find you could run:
```
-dedicated -game dota +map dota
```
Source of that information is on this guide: https://kb.firedaemon.com/support/solutions/articles/4000086947-dota-2
(The third-party application they suggest should not be needed.)

I don't know how accurate this guide is or if the launch options will even work. You'll need to do the configuration yourself and see what you can do. I did not even know you could host your own Dota 2 server to be honest.

Locking thread, Good luck!
