### ISSUE TITLE
Some important ideas to implement

### ISSUE THREAD

**Issue by dkdue** [n0tic/SteamServerCreationTool#4]
Hello, a while ago we got in touch by email, I think you did not receive my email with several ideas that could improve the application, I have been creating dedicated servers since 2015 and I think they are very necessary, I present a small list:
1. Auto Updater (necessary for the servers to update without having to be present or having to do it manually)
2. Discord (send notices to discord of the server status, Starting, stopping, crash and update available)
3. Add reboot time (necessary to send reboot messages due to update or daily reboot of the server to the discord)
An example would be to put that the server restarts every day at 06:00 AM and notify by discord 15 minutes in advance, the same when it finds an update.

I am delighted with the application, it would be great if you opened a discord channel so that people can help you or contribute more ideas, thanks for your work

**Comment by n0tic** [comment]
**Hello @dkdue** 
You are correct in you assumption that the email was lost. Totaly missed the reply!

First of - This application aims to be a very easy, quick and lightweight tool.

1. To add a feature such as the "Auto Updater" I would need to research how to get the current build/version and compare it to the currently installed server. Plausable.

Right now my system is creating the batch file which updates the server before starting the server, as well as keeping it alive with crash prevention etc. The StartServerScript.bat file is what I'm refering to.

2. A Discord bot is plausable to connect in the future. I will look into it.

3. A notification system is also plausable - When it comes to the discord part.
Sending a message to the live game server is a bit overkill since there are too many to get working.


**I'm very pleased to hear that my application is being used and liked!**
All of the ideas above are great additions to the applications. However, I like the ideas but I cannot give you a definitive answer to WHEN or IF any idea will be implemented into the application. I will do my research and see how I should proceed.

Right now Im focusing on real life and have very limited free time to do any research or work on this application. This project is not abandoned though. Just letting you know!

To address the last thing you said, about discord. Thats actually something I can do in the coming days. I will setup a discord server dedicated to this project wich should provide a direct link with a future community.

Im really not liking the current UI and are experimenting with yet another style. I would appreciate some feedback regarding the new, unreleased, style if you have a second. Thanks in advanced!
[V3UI](http://bytevaultstudio.se/ShareX/rGchNsnSpi.png)

**Thanks for the feedback! Its really fun hearing that someone appreciate my work.**

**Comment by dkdue** [comment]
I'm glad then to have written to you here.

1. I send you the code of an application that does it, you can investigate it and adapt it to your code ( https://github.com/WindowsGSM/WindowsGSM ) The problem with this application is that you have to create plugins, so if someone does not do it, you cannot create a server, hence your application is better for me.

2. It is clear that the most important thing is real life, family, partner, friends, etc, but I am very happy that you do not abandon it, this application has a lot of potential and if you add everything described, you will make it the best steamcmd application that exists.

3. Another option that just occurred to me, would be to create a website that manages the application, right now I don't remember what that is called, but it would be a way to have a remote control (imagine that you are working and people asking you to update the server and you can't because you're not at home) is another example, that's why the auto-updater is very important. (sorry for insisting so much on this issue).

4. For a UI I am not the best option to help you, I like the current one and I like the one in the photo that you just showed me or you could have it all by tabs.
- Tab 1: Install SteamCMD, download link, choose where to install it and below a log incorporated into the application to see the installation log.
- Tab 2: Choose the server, where to install the server and the integrated log to see the log
- Tab 3: Servers management, a table with the list of installed servers, each server with its built-in log to continue viewing the server logs, etc. etc.

For now I can only think of that

I like to support projects that I think are well done and meet my needs as a server creator, thanks to you for creating this application that looks great

**Comment by n0tic** [comment]
Hello and thank you once again for the encuragement!

I will investigate and do some research about how to proceed with this. 
Thank you for the provided references!

If you come up with some new ideas, feel free to open this thread again!

Cheers, N
