### ISSUE TITLE
Keyboard character shortcut to quickly find the server name

### ISSUE THREAD

**Issue by MedGR450** [n0tic/SteamServerCreationTool#5]
Hello, it's a bit frustrating when searching for servers, especially if you host a lot.
A viable solution to this is removing the server ID numbers from the start and make them at the end of the server name
![image](https://user-images.githubusercontent.com/22678541/143151731-070feaab-8c0d-42e4-9692-4b3fb47331b8.png)

Also thanks a lot for this useful app! What makes it unique is that it supports ALL dedicated servers on Steam, unlike other graphical solutions like WindowsGSM.
This makes life easier on a Windows Server.

**Comment by MedGR450** [comment]
I just realized we can search for a game server but that's a few more clicks.
I think adding shortcut keys will be a better QoL addition.

**Comment by n0tic** [comment]
Designing an application is not my cup of tea. The current design Is what I could do without having to sacrifice a clean UI look. At first the search was on the main window (Among a lot of other settings/functions) but I hated the design and split it up into 4 windows. I had to do it in order to get the application looking cleaner. 

This is why the search function is present, but on another window. The "search window" and the "main window" are still linked though. 
If you search for a server and select it on the "search window" it automatically gets selected on the "main window". You can also double click an item found by searching to automatically close the "search window" and have it selected in the "main window". A bit confusing reading the sentences but I'm sure you'll get how it works. Should be fairly staight forward.

However, I'm open to suggestions or feedback regarding anything related to the application.
How should this shortcut key work? I'm a bit confused here so please elaborate.


Also, Im currently working on updating the UI and a few other/more features.
Not promising anything though.

![Preview](https://i.imgur.com/cgsBiwA.png "Preview")

PS. Time is limited as work has priority. Hope you understand.  Thanks!
