### ISSUE TITLE
please add the support of Counter-Strike 1.6 dedicated server.

### ISSUE THREAD

**Issue by F0RTYS3V3N** [n0tic/SteamServerCreationTool#7]
Counter-Strike
appid 10 Not Supported Please Add

**Comment by n0tic** [comment]
Hello! Sorry for a late response.

If I'm not mistaken, the ID of the "Counter-Strike 1.6 dedicated server" is **90**. Which would be "Half-Life Dedicated Server".
App ID 10 is the playable version of the game. 

However, there seem to be a problem installing the dedicated server. I tried this myself a minute ago and got an error 0x6 which states there are some problems on Valves server-side.

_"It's an error that means "Missing decryption key" and has been occurring since the last Beta was pushed."_

However, please try this yourself and see if you can get it to work. It seems this is a try again kind of problem.

Cheers, ~N

**Comment by n0tic** [comment]
Leaving this as a reference for others that may encounter the same problem in the future.

I've tried installing app (90) "Half-Life Dedicated Server" several times and it has failed. 
However, I tried going into "Manage Servers" and used the "Update Server" feature with success.

If this solved the issue for you, please open an "Issue Ticket" and I'll take another look at this potential problem as I cannot replicate the issue myself at this time.

Cheers, ~N
